AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Router Service for HR Assistant
Parameters:
  DbHost:
    Type: String
    Default: shortline.proxy.rlwy.net
  DbPort:
    Type: Number
    Default: 49692
  DbName:
    Type: String
    Default: railway
  DbUser:
    Type: String
    Default: root
  DbPassword:
    Type: String
    Default: fwbmUuEstVNVheIibURuBIOhlveCVZjo
  Port:
    Type: Number
    Default: 5000
  NodeEnv:
    Type: String
    Default: development
  JwtSecret:
    Type: String
    Default: aVeryLongAndRandomSecretKeyForYourApp
  AdminBackendUrl:
    Type: String
    Default: https://admin-api.example.com/api
  UserBackendUrl:
    Type: String
    Default: https://user-api.example.com/api
  AllowedOrigins:
    Type: String
    Default: http://localhost:3000,https://example.com
Resources:
  RouterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://router-service-deployment-bucket/f3d2bad0f5ccf31f04b9ce70425be1bf
      Handler: src/serverless.handler
      Runtime: nodejs16.x
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          DB_HOST:
            Ref: DbHost
          DB_PORT:
            Ref: DbPort
          DB_NAME:
            Ref: DbName
          DB_USER:
            Ref: DbUser
          DB_PASSWORD:
            Ref: DbPassword
          PORT:
            Ref: Port
          NODE_ENV:
            Ref: NodeEnv
          JWT_SECRET:
            Ref: JwtSecret
          ADMIN_BACKEND_URL:
            Ref: AdminBackendUrl
          USER_BACKEND_URL:
            Ref: UserBackendUrl
          ALLOWED_ORIGINS:
            Ref: AllowedOrigins
      Events:
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId:
              Ref: RouterApi
        ProxyPath:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: RouterApi
    Metadata:
      SamResourceId: RouterFunction
  RouterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''*'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
        AllowOrigin: '''*'''
    Metadata:
      SamResourceId: RouterApi
Outputs:
  RouterApi:
    Description: API Gateway endpoint URL for Router Service
    Value:
      Fn::Sub: https://${RouterApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  RouterFunction:
    Description: Router Lambda Function ARN
    Value:
      Fn::GetAtt:
      - RouterFunction
      - Arn
