version = 0.1
[default.deploy.parameters]
stack_name = "router-service"
resolve_s3 = true
s3_prefix = "router-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DbHost=\"shortline.proxy.rlwy.net\" DbPort=\"49692\" DbName=\"railway\" DbUser=\"root\" DbPassword=\"fwbmUuEstVNVheIibURuBIOhlveCVZjo\" Port=\"5000\" NodeEnv=\"development\" JwtSecret=\"aVeryLongAndRandomSecretKeyForYourApp\" AdminBackendUrl=\"https://9qgityvc65.execute-api.ap-south-1.amazonaws.com/Prod\" UserBackendUrl=\"https://6gdnzsir85.execute-api.ap-south-1.amazonaws.com/Prod\" AllowedOrigins=\"http://192.168.0.203:3000,http://localhost:3000,http://localhost:5173,http://10.80.5.110:3000,http://192.168.58.157:3000,http://192.168.83.157:3000,https://vipraco-frontend.vercel.app\""
image_repositories = []
