service: hr-assistant-router-service

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 256
  timeout: 30
  environment:
    # Environment variables are loaded from .env file
    JWT_SECRET: ${env:JWT_SECRET}
    SUPABASE_JWT_SECRET: ${env:SUPABASE_JWT_SECRET}
    ADMIN_BACKEND_URL: ${env:ADMIN_BACKEND_URL}
    USER_BACKEND_URL: ${env:USER_BACKEND_URL}
    NODE_ENV: ${env:NODE_ENV, 'development'}
    ALLOWED_ORIGINS: ${env:ALLOWED_ORIGINS}

functions:
  api:
    handler: src/serverless.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 5000
  dotenv:
    path: ./.env 